// SPDX-License-Identifier: GPL-2.0
//! Build script: copies kernel/polaris_abi.rs into the userspace crate.
//!
//! This keeps the ioctl structs, enums, and constants in a single source
//! of truth under kernel/polaris_abi.rs.  Any change to the ABI is
//! automatically picked up by both the kernel module and all userspace
//! programs (polarisd, workloads, polarisctl) that depend on libpolaris.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let abi_src = manifest_dir.join("../kernel/polaris_abi.rs");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let abi_dst = out_dir.join("polaris_abi_generated.rs");

    // Re-run if the ABI source changes
    println!("cargo:rerun-if-changed={}", abi_src.display());

    let content = fs::read_to_string(&abi_src).expect("failed to read kernel/polaris_abi.rs");

    // Prepend a header so the generated nature is clear.
    // Use plain `//` (not `//!`) because the content is `include!`-ed
    // after the module-level doc comment in types.rs.
    let header = format!(
        "// AUTO-GENERATED from {} — DO NOT EDIT\n// Regenerated by libpolaris/build.rs on every build.\n\n",
        abi_src.display()
    );

    fs::write(&abi_dst, header + &content).expect("failed to write generated ABI file");
}
